version: "3.8"

networks:
  kong-net:
    driver: bridge

volumes:
  kong-data: 
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local

services:
  kong-database:
    image: postgres:15
    container_name: kong-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kong}
      POSTGRES_DB: ${POSTGRES_DB:-kong}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kong}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kong-net

  kong-migrations:
    image: hewenyulucky/kong:${KONG_VERSION:-3.9.0-ubuntu}
    container_name: kong-migrations
    restart: "no"
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: ${POSTGRES_USER:-kong}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD:-kong}
    networks:
      - kong-net
    command: "kong migrations bootstrap"
  
  # Redis服务，用于jwt-redis-validator插件,需要密码
  kong-redis:
    image: redis:8.0.1-alpine
    container_name: kong-redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-kong}
    networks:
      - kong-net

  kong:
    image: hewenyulucky/kong:${KONG_VERSION:-3.9.0-ubuntu}
    container_name: kong
    restart: always
    depends_on:
      - kong-database
      - kong-redis
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: ${POSTGRES_USER:-kong}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PG_POOL_SIZE: 5
      KONG_PG_TIMEOUT: 5000
    ports:
      - "${KONG_HTTP_PORT:-8000}:8000" # Kong Proxy (HTTP)
      - "${KONG_HTTPS_PORT:-8443}:8443" # Kong Proxy (HTTPS)
      - "${KONG_ADMIN_HTTP_PORT:-8001}:8001" # Kong Admin API (HTTP)
      - "${KONG_ADMIN_HTTPS_PORT:-8444}:8444" # Kong Admin API (HTTPS)
      - "${KONG_MANAGER_PORT:-8002}:8002" # Kong Manager UI
    volumes:
      - kong-data:/usr/local/kong
      - ./kong.conf:/etc/kong/kong.conf
    networks:
      - kong-net