name: Build Kong Configs Docker Image

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-push:
    environment: DOCKERHUB
    runs-on: ubuntu-latest
    
    # 从另外的仓库获取代码 
    steps:
    - name: Clone configs repository
        run: |
          git clone https://github.com/hewenyu/kong-plugins-configs.git
          cd kong-plugins-configs
          echo "CONFIGS_COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: /kong-plugins-configs
        push: true
        tags: |
          hewenyulucky/kong-configs:latest
          hewenyulucky/kong-configs:${{ env.CONFIGS_COMMIT_SHA }}
        no-cache: true